"""add bmi, bfp, muscle and visceral tables

Revision ID: 1a1fccd3d941
Revises: 783b1d734514
Create Date: 2018-04-16 01:20:59.079755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1fccd3d941'
down_revision = '783b1d734514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bfp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('female_up_limit', sa.Float(), nullable=True),
    sa.Column('male_up_limit', sa.Float(), nullable=True),
    sa.Column('conclusion', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bmi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('up_limit', sa.Float(), nullable=True),
    sa.Column('conclusion', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('muscle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('female_up_limit', sa.Float(), nullable=True),
    sa.Column('male_up_limit', sa.Float(), nullable=True),
    sa.Column('conclusion', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visceral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('up_limit', sa.Float(), nullable=True),
    sa.Column('conclusion', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visceral')
    op.drop_table('muscle')
    op.drop_table('bmi')
    op.drop_table('bfp')
    # ### end Alembic commands ###
