"""add user_measurements table

Revision ID: 2b8cb090c298
Revises: 5d09ccff49bd
Create Date: 2018-03-10 22:43:00.446399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b8cb090c298'
down_revision = '5d09ccff49bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('measurement', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['measurement'], ['measurements.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_measurements')
    # ### end Alembic commands ###
