"""add measurements table

Revision ID: 5d09ccff49bd
Revises: cc63ba0f7213
Create Date: 2018-03-10 22:12:19.580478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d09ccff49bd'
down_revision = 'cc63ba0f7213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('fullname', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurements_name'), 'measurements', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurements_name'), table_name='measurements')
    op.drop_table('measurements')
    # ### end Alembic commands ###
